In [1]:
import numpy as np

In [17]:
arr1 = np.array([2,5,8])
arr2 = np.array([3,6,9])
# arr = np.concatenate((arr1,arr2))
newarr1 = np.hstack((arr1,arr2))
newarr2 = np.vstack((arr1,arr2))
newarr3 = np.dstack((arr1,arr2))
print(newarr1)
print(newarr2)
print(newarr3)

[2 5 8 3 6 9]
[[2 5 8]
 [3 6 9]]
[[[2 3]
  [5 6]
  [8 9]]]


In [8]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis = 1)

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [13]:
arr1 = np.array([2,5,8])
arr2 = np.array([3,6,9])

arr = np.stack((arr1, arr2),axis = 1)

print(arr)


[[2 3]
 [5 6]
 [8 9]]
