In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,2,3)
print(newarr.base)
# view array

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.reshape(-1))

[1 2 3 4 5 6]
