In [3]:
import numpy as np

In [10]:
arr =np.array([1, 2, 3, 4, 5, 6])

n = np.where(arr == 3)
print(n)

(array([2], dtype=int64),)


In [11]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


In [12]:
#even values
arr =np.array([1, 2, 3, 4, 5, 6])

n = np.where(arr%2 == 0)
print(n)

(array([1, 3, 5], dtype=int64),)


In [14]:
#odd values
arr =np.array([1, 2, 3, 4, 5, 6])

n = np.where(arr%2 == 1)
print(n)

(array([0, 2, 4], dtype=int64),)


In [15]:
arr = np.array([2,5,6,8,9])

x = np.searchsorted(arr,6)
print(x)

2


In [19]:
arr = np.array([2,5,6,8,9])

x = np.searchsorted(arr,6,side='right')
print(x)

3


In [18]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)


2


In [20]:
#ADD  a array index predict
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]
