In [2]:
from numpy import random

In [20]:
x = random.randint(100)

print(x)

17


In [28]:

x = random.rand()
y = random.rand(3)
z = random.rand(3,2)

print(x)
print(y)
print(z)

0.07608719814123643
[0.03738542 0.68126567 0.31223008]
[[0.50635285 0.99894594]
 [0.42339029 0.06289961]
 [0.5991277  0.54149322]]


In [22]:
x = random.randint(100,size=(4))

print(x)

[ 6 68 62 84]


In [25]:
x = random.randint(100,size=(4,3))

print(x)

[[95 99 20]
 [ 7 92 99]
 [ 9 76 26]
 [37 33 96]]


In [30]:
#random choice from array
x = random.choice([ 6 ,8 ,2 ,4])
print(x) #output: randomly chosen number between the given range of numbers in an array 


2


In [32]:
x = random.choice([ 6 ,8 ,2 ,4],size=(2,3))
print(x)

[[2 4 2]
 [6 8 2]]
