In [1]:
from numpy import random

In [5]:
x = random.choice([7,0,1,3],p = [0,0.5,0.3,0.2],size=(50))
y = random.choice([7,0,1,3],p = [0,0.5,0.3,0.2],size=(3,3))
print(x)
print(y)

[0 0 0 3 1 3 1 0 0 0 0 0 1 1 0 0 0 0 3 3 1 0 1 1 3 1 0 1 1 1 1 0 1 0 0 3 0
 0 1 1 3 3 3 3 1 0 0 3 3 1]
[[3 1 1]
 [1 0 0]
 [1 0 0]]
